# Generated by Django 5.1.1 on 2024-10-05 05:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uz', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fruit_types/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fruits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fruit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='agro.fruittype')),
            ],
        ),
    ]
